import type { PurpleCloudProductRow } from './purpleCloudSizing'
import grid from './data/purpleCloudProductGrid.json'

/** Full PurpleCloud commercial grid (generated by scripts/build-purplecloud-grid.mjs). */
export const PURPLE_CLOUD_PRODUCT_GRID = grid as PurpleCloudProductRow[]
